server:
  port: 3344
eureka:
  instance:
    hostname: cloud-config-center #服务端的实例名称
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          #git仓库地址
          uri:
          #搜索的目录
          search-paths:
      #读取的分支
      label: master
